### ISSUE TITLE
`dataspace` macro in HLL is confusing

### ISSUE THREAD

**Issue by howell** [tonyg/syndicate#20]
The following program

```racket
(spawn (on (message "hello")
           (printf "got hello\n")))
(spawn (on-start (printf "hello\n")
                 (send! "hello")))
```

prints `hello` followed by `got hello` as expected. But putting inside a dataspace, like:

```racket
(dataspace
 (spawn (on (message "hello")
            (printf "got hello\n")))
 (spawn (on-start (printf "hello\n")
                  (send! "hello"))))
```

only prints `hello`.

I'm pretty sure this is unexpected behavior, so unless otherwise noted I'll take a look at what's going on.

**Comment by tonyg** [comment]
I think this is to do with the way the `dataspace` macro is not quite symmetric with the `spawn` macro: while a `spawn`ed actor runs until it has no facets left, a `dataspace` runs until its *boot actor* terminates; and the boot actor is just the script inside the `(dataspace ...)` form.

For example,

```racket
(dataspace)
```

will start a dataspace which terminates very quickly, while

```racket
(dataspace (forever))
```

will start a dataspace that will never terminate, even though it is completely inert.

Here's a variation on your example program that prints both `hello` and `got hello`:

```racket
(dataspace
 (spawn (on (message "hello")
            (printf "got hello\n")))
 (spawn (on-start (printf "hello\n")
                  (send! "hello")))
 (forever))
```

**Comment by tonyg** [comment]
**Q:** What should we do here? Can we think of a better way for the `dataspace` macro to behave?

The way it's working now is that an implicit `(quit-dataspace)` is being performed at the end of the boot actor. The idea is that writing a program that used `react/suspend` (and variations like `forever`) to delay reaching it would allow a reasonable level of application-specific control over `quit-dataspace` without exposing it per se (since it's a bit grody; see #6).

**Comment by tonyg** [comment]
Better is to just have it never automatically issue `quit-dataspace`. Instead, there's now a `quit-dataspace!` HLL procedure. The two procedures `spawn*` and `dataspace` are now almost the same except the latter creates a dataspace in addition to an actor.
